# Generated by Django 3.1 on 2020-11-07 18:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newtaskform',
            old_name='task',
            new_name='name',
        ),
    ]
