# Generated by Django 3.1 on 2020-11-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20201107_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newtaskform',
            name='name',
            field=models.TextField(max_length=256),
        ),
    ]
