# Generated by Django 3.1 on 2020-11-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('notes', '0004_auto_20201107_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit', models.TextField(max_length=256)),
            ],
        ),
    ]
