# Generated by Django 3.1 on 2020-11-07 21:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('notes', '0005_editfield'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editfield',
            old_name='edit',
            new_name='change',
        ),
    ]
