# Generated by Django 3.1 on 2020-11-07 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('notes', '0006_auto_20201108_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.newtaskform')),
            ],
        ),
    ]
