# Generated by Django 3.1.3 on 2020-11-10 18:01

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('notes', '0007_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='newtaskform',
            name='time',
            field=models.DateField(auto_now_add=True,
                                   default=datetime.datetime(2020, 11, 10, 18, 1, 32, 29773, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
