# Generated by Django 3.1.3 on 2020-11-10 19:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('notes', '0009_auto_20201110_2239'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EditField',
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
