# Generated by Django 3.1.3 on 2020-11-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('notes', '0012_auto_20201110_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newtaskform',
            name='creation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newtaskform',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
